name: Deploy to ESXi

on:
  push:
    branches:
      - main  # Change this to your main branch name if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y vagrant
        vagrant plugin install vagrant-vmware-esxi

    - name: Set up Vagrant
      run: |
        vagrant up --provider=vmware_esxi

    # Add additional steps here if needed
